version: '3.7'
services:
  remote_debug:
    build:
      context: .
    volumes:
      - .:/go/src/github.com/bitrise-io/tech-talk
    ports:
      - 2345:2345
      - 9999:9999
    security_opt:
      - "seccomp:unconfined"